### ISSUE TITLE
Need to upgrade to use Python3

### ISSUE THREAD

**Issue by genterminl** [pturmel/lsdrv#11]
Running from git head:
```
jack $./lsdrv 
  File "./lsdrv", line 323
    os.mkdir('/dev/block', 0755)
                              ^
SyntaxError: invalid token
```
It seems this is due to Python 3 (3.6.5 in my case) where octals apparently need to be specified Oo0755.  However, changing that line leads to other errors (missing parens for print is the next one) and explicitly running with Python2 it works fine.  
I'm not a Python programmer, so I don't know how much effort this requires, or if there is simply a way to explicitly request Python2 in the meantime.

**Comment by CRCinAU** [comment]
@pturmel - Just wondering if you got anywhere with this?

I've used the script over the years to check my strages on Proxmox - but it no longer ships with Python 2.7 at all...

By changing the `print` statements to `print(xxxx)` - and then the permissions to `0oXXX` - I've got to this point, and now I don't know what to do here:
```
Traceback (most recent call last):
  File "/root/bin/./lsdrv", line 423, in <module>
    probe_block('/sys/block/'+x)
  File "/root/bin/./lsdrv", line 342, in probe_block
    blk.__dict__.update(extractvars(runx(['blkid', '-p', '-o', 'udev', '/dev/block/'+blk.dev])))
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/bin/./lsdrv", line 165, in extractvars
    for mo in varsre.finditer(buffer):
              ^^^^^^^^^^^^^^^^^^^^^^^
TypeError: cannot use a string pattern on a bytes-like object
```

**Comment by genterminl** [comment]
It looks to me like the last commit to the code was over five years ago, so I have to wonder if this is now abandonware?

**Comment by pturmel** [comment]
Well, I'm still alive, but yes, low priority for quite some time now.  Every time I look, I realize it needs substantial work to make it async-friendly in addition to the byte/string distinctions needed.

**Comment by CrimsonGlory** [comment]
I've just opened a PR with code changes that make the script work both in python 2 and 3.
https://github.com/pturmel/lsdrv/pull/14

**Comment by poddmo** [comment]
PR #14 works for me. I'm very glad to have lsdrv back in my life.
Tested on Ubuntu 22.04.5 LTS x64

I applied the patch below to make is ascii-only:
```
--- lsdrv.orig  2025-05-05 15:01:58.052934155 +1000
+++ lsdrv       2025-05-05 15:12:55.045551145 +1000
@@ -504,7 +504,7 @@
                oPVs = " (w/ %s)" % ",".join(otherPVs)
        else:
                oPVs = ""
-       print("%s └VG %s %s%s %s free {%s}" % (indent, vg.name, vg.size, oPVs, vg.free, vg.uuid))
+       print("%s +VG %s %s%s %s free {%s}" % (indent, vg.name, vg.size, oPVs, vg.free, vg.uuid))
        if vg.shown:
                return
        show_blocks(indent+"  ", vg.LVs)
@@ -513,8 +513,8 @@
 #-------------------
 # Given an indent level and list of block device names, recursively describe
 # them.
-continuation = ('│', '├')
-corner = (' ', '└')
+continuation = ('|', '+')
+corner = (' ', '+')
 def show_blocks(indent, blocks):
        for blk in blocks:
                if blk == blocks[-1]:
```
