### ISSUE TITLE
Error if non-active vg/lv are present

### ISSUE THREAD

**Issue by hwk** [pturmel/lsdrv#7]
## The error seems unrelated to the "Couldn't find device with uuid". That only ensures that /vg_newlv_new isn't active.

root@elefant:/home/kraush/work# lvscan
  ACTIVE            '/dev/stor1/stor1' [10.90 TiB] inherit
  ACTIVE            '/dev/vg_vnew/lv_new' [3.64 TiB] inherit
  ACTIVE            '/dev/vg_current/lv_cur_1' [1.20 TiB] inherit
  Couldn't find device with uuid LkHjyU-T4EP-Ta5B-sf0D-kc0r-2iZA-F0A8Lm.
  Couldn't find device with uuid TLYwDv-aNDB-TM6g-oLTf-pjdj-TN4E-Yr8KHQ.
  Couldn't find device with uuid CP2BAI-oZCw-woFK-MfLN-jAFD-66mj-aCLz3S.
  inactive          '/dev/vg_new/lv_new' [7.89 TiB] inherit
root@elefant:/home/kraush/work# lsdrv
Traceback (most recent call last):
  File "/usr/local/bin/lsdrv", line 469, in <module>
    devstat = os.stat('/dev/'+vg_name+'/'+lv_name)
OSError: [Errno 2] No such file or directory: '/dev/vg_new/lv_new'

**Comment by romanrm** [comment]
It seems like this issue also causes it to fail with LVM Thin volumes. The thinpool itself is listed in the `lvs` output, but it's never present as a device file in /dev/vgname/ (even while active).

> Traceback (most recent call last):
>   File "[...]/lsdrv", line 481, in <module>
>     devstat = os.stat('/dev/'+vg_name+'/'+lv_name)
> OSError: [Errno 2] No such file or directory: '/dev/vgname/thin'

**Comment by CRCinAU** [comment]
Just as a note, this is still an issue today.

A quick hack to make it work is to change line 479 to:
```python
if lv_type == "cache-pool" or lv_type == "thin-pool":
```
